- CMakeLists.txt
- include/crypto.hh
- src/random.cc
The 2.0.0 release of uvgRTP fails to build on CentOS7, because :
- the gcc-c++ compiler doesn't support the c++17 standard, which is
required to compile the crypto.hh file
- the getrandom() function isn't available in the libc
This pull request adds CentOS7 build support.
The modified files are :
- CMakeLists.txt : the availability of the getrandom() function is checked.
If it exists, the HAVE_GETRANDOM preprocessor definition is added
- src/random.cc : if HAVE_GETRANDOM isn't defined, a syscall equivalent to
the getrandom() functions is called
- include/crypto.hh : the c++17 code is replaced by a code that compiles with
the CentOS7 compiler (c++11)
> build: Support for CentOS7

- src/dispatch.cc
- src/formats/h265_pkt_handler.cc
- src/formats/h266_pkt_handler.cc
- src/frame.cc
- src/holepuncher.cc
- src/media_stream.cc
- src/pkt_dispatch.cc
- src/queue.cc
- src/rtcp.cc
- src/rtcp/app.cc
- src/rtcp/bye.cc
- src/rtcp/receiver.cc
- src/rtcp/sdes.cc
- src/rtcp/sender.cc
- src/session.cc
- src/socket.cc
- src/srtp/base.cc
There where a lot of if statements to check if a new operation would return null
Because "new" can never return null, at least in the official standard, we remove those.
I did no put any effort to in correcting anything but removing those if's
The cleanings I removed would never have been called anyway, so no break should be happening.
I think it is necessary to replace a lot of those pointers with smart pointers and do the cleaning in RAII fashion, 
but that should be part of another PR
> common: #23 removed useless if statements for nullptr checks

- src/zrtp.cc
- src/zrtp/zrtp_receiver.cc
#36 Because of refactoring there where some leftover minus signs
> zrtp: Removed wrong minus signs in front of error return codes

- .gitignore
- CMakeLists.txt
- cmake/FindDependencies.cmake
- cmake/ProjectDetails.cmake
- cmake/Versioning.cmake
- cmake/uvgrtpConfig.cmake
- cmake/uvgrtp_version.cpp.in
- include/uvgrtp_version.h
- packaging/CMakeLists.txt
- packaging/Description.txt
- packaging/License.txt
- packaging/Readme.txt
- packaging/Welcome.txt
- test/CMakeLists.txt
- test/TestGTest.cpp
- test/main.cpp
Primary changes are:
- Versioning integrated in cmake build system with library for version usage in end user programs
- New minimum CMAke required version is 3.14
- Created install capabilities. Allows uvgRTP to be used in different scenarios for win and lin (mac-os still missing)
- Added testing environment with automatically fetched google test and some example test code.
- Added packaging capabilities (and some placeholders that have to be changed)
> build: Completely Redesigned CMake files (#44)

- CMakeLists.txt
- cmake/uvgrtp.pc.in
The problem of #77 is that the installed header does not reflect the macro `__RTP_NO_CRYPTO__` added by the cmake with pkg-config.
When the user compiles their program with their own -D flag, it would be fine. However, pc config file generated by cmake does not have that flag.
This PR is to resolve that problem.
> build: add macro to pc generation with cmake variable

- src/frame.cc
- src/rtp.cc
Hi, 
I ran into a bit of a problem trying to use the extension header. I am reasonably confident this fix is correct for the one byte header case, however, the RFC also specifies a Two-Byte Header, which I'm not certain it is supported here at all.
https://datatracker.ietf.org/doc/html/rfc5285#section-4.2 
I hope this helps, I'm afraid I don't have any experience contributing to open source projects.
:-) Kolja
- When setting the len field of the header, a bad offset of the source
pointer was used
- The len field of the header is a uint16 specifying payload length in
multiples of 32 bit
- Also, subtract the extension header length from the payload length
> rtp: fix up handling of extension header

- src/formats/h26x.cc
Fixed a bug causing a small packet handling to continue to the "large" packet handling, where it should never go.
Also added a fix removing the limitation of at least 3 bytes for the NALU, which should not be needed
> H26x packet handling fixes

- CMakeLists.txt
PR fixes a compiler error about:
```
CMake Error at CMakeLists.txt:21 (set_target_properties):
set_target_properties called with incorrect number of arguments
```
When compiling the project with cmake within a ROS1 environment, the compiler termites with an error about "CMake Error at CMakeLists.txt:21 (set_target_properties): set_target_properties called with incorrect number of arguments".
Fixed by inserting cmake variables (within the command "set_target_properties") in double quotes.
I successfully tested the fix with both the standard build instructions for cmake, contained in the readme, and in the ROS1 environment. Please let me know if you can also double check this on your side.
> build: fix error set_target_properties called with incorrect arguments number

- src/rtcp.cc
LSR means middle 32 bits of the 64-bit NTP timestamp of previous SR so it seems that it should be changed
> Modify LSR

- src/rtcp.cc
There was a bug where if an error occurs in the generate_report() function the lock would not unlock and the next call would double lock and cause an exception
> rtcp: Prevent double locking in generate_report

- include/uvgrtp/debug.hh
A zero-length `__VA_ARGS__` would result in a trailing comma, which is a syntax error. GCC supports zero-length `__VA_ARGS__` with an extension to eat the comma: `, ## __VA_ARGS__`.
But this is not standard and since CMakeLists.txt sets `-Wall -Wextra -Wpedantic`, we get a ton of spurious warnings when building with clang:
uvgRTP-master/include/uvgrtp/debug.hh:56:27: warning: token pasting of ',' and __VA_ARGS__ is a GNU extension [-Wgnu-zero-variadic-macro-arguments]
"", __func__, ##__VA_ARGS__)
^
So the function uvgrtp_debug can be implemented as a variadic function (which unlike variadic macros, do support zero-length va_list).
> common: Remove GNU extension (, ##__VA_ARGS__).

- cmake/uvgrtp.pc.in
I was building with -DDISABLE_CRYPTO=ON (for now) and ended up with -D__RTP_NO_CRYPTO__ in:
pkg-config --libs uvgRTP
(instead of `pkg-config --cflags uvgRTP`)
which was giving me compile errors like:
build/arm64-apple-darwin/include/uvgrtp/crypto.hh:32:10: fatal error: 'cryptopp/aes.h' file not found
#include <cryptopp/aes.h>
^~~~~~~~~~~~~~~~
Also, since it ends up in uvgrtp.pc, should `__RTP_NO_CRYPTO__` be renamed to `UVGRTP_NO_CRYPTO`?
> build: Move UVGRTP_CXX_FLAGS to CFlags in uvgrtp.pc.

- src/rtcp.cc
This was not shifted, thus causing the wraparound to not be added
> rtcp: shift RR sequence cycles on wraparound

- include/uvgrtp/rtcp.hh
- src/rtcp.cc
Currently, this function only creates a shallow copy of the name and payload, so if the original pointers are deleted it leads to undefined behavior. 
```cpp
rtp_error_t uvgrtp::rtcp::send_app_packet(const char* name, uint8_t subtype,
size_t payload_len, const uint8_t* payload)
{
std::string str(name);
rtcp_app_packet packet = { name, subtype, payload_len, payload };
packet_mutex_.lock();
if (!app_packets_[name].empty())
{
LOG_WARN("Adding a new APP packet for sending when %llu packets are waiting to be sent",
app_packets_[name].size());
}
app_packets_[name].push_back(packet);
packet_mutex_.unlock();
return RTP_OK;
}
```
My implementation handles allocation/deallocation internally.
> rtcp: deepcopy APP packet data and handle it internally

- include/uvgrtp/rtcp.hh
- src/rtcp.cc
Currently there is no way of knowing what the interval is
> rtcp: add a public getter function for interval_ms_

- include/uvgrtp/socket.hh
- src/srtp/srtp.cc
common: Remove stray quote from include to silence warning
> common: Remove stray quote from include to silence warning

- CMakeLists.txt
When trying to build under Fedora 36, CMake would give the following output
```
-- Checking for one of the modules 'libcrypto++'
libcrypto++ not found. Encryption will be disabled
```
Fedora OS install this package as 'cryptopp'
> build: Added alternative search name for libcrypto++

- src/formats/h26x.cc
If the input data has a zero after the start code with an offset of 1
Meaning case where basically:
(BIG_ENDIAN)
`prev_value32 = 0xXX000000;`
`cur_value32 = 0x0100XXXX;`
The current version of SCL does not find the actual start code because it's assuming no zeros in the current byte.
> formats: fix a bug in SCL, sequence like \0\0\0\1\0 not detected

- src/poll.cc
Hello, 
I have noticed that my program takes an unnecessary amount of CPU and ran a profiler in Visual Studio. 
It showed that the *poll* function in rtcp runner is very CPU heavy, although it's not doing much. Long story short the wait time of *::select* function was not fully implemented, and was always 0, causing the function to busyloop. I fixed it by finishing the wait time calculation for microseconds aswell. After this adjustment, the CPU load of my program was roughly halved.
> rtcp: fix socket selection busylooping in rtcp polling

- include/uvgrtp/media_stream.hh
- include/uvgrtp/rtcp.hh
- include/uvgrtp/util.hh
- src/media_stream.cc
- src/rtcp.cc
- src/rtp.cc
- src/rtp.hh
An alternative solution for #180. Here, we share an SSRC between the objects in a thread-safe way. No intrusion on the API, as opposed to #182.
> config: allow for custom SSRC. Added thread safety

- include/uvgrtp/rtcp.hh
- src/rtcp.cc
> rtcp: add thread safety for prticipants_ data structure

- include/uvgrtp/rtcp.hh
- src/rtcp.cc
- src/rtcp_packets.cc
- src/rtcp_packets.hh
I started from scratch on a new branch. This is my new proposition
> rtcp: add hooking for sending APP packets

- src/context.cc
- src/random.cc
- src/random.hh
I hit a deadlock when generate() was calling `syscall(SYS_getrandom, buf, n, 0)` on an embedded system. I went with a standard solution, which cut down on some code and should be more portable. I also removed the apparently unused `generate_64()` function. If that function is truly needed, I can update to include it.
Tested with gcc on linux, unable to test on windows.
> random: Replace system random calls with STL

- src/socket.cc
- test/test_2_rtp.cpp
- test/test_7_ipv6.cpp
- test/test_common.hh
Added multicast address detection in `uvgrtp::socket::bind` `uvgrtp::socket::bind_ip6`
Tests added to test_2_rtp and test_7_ipv6
Tested on:
- Windows 10 with MSVC
- Ubuntu 20.04.6 LTS Linux aarch64 with gcc
> common: Added multicast bind support for ipv4 and ipv6

- src/debug.hh
- src/hostname.cc
Hi, continuing from [here](https://github.com/ultravideo/uvgRTP/issues/216), this is the pull request with the requested changes (and another convenient one for android development)
Changes in this PR:
- src/hostname.cc: Fix compilation when targeting Android SDK min versions < 28.
- src/debug.hh: on Android, print UVG_LOG_*** messages to Android Logcat instead of stdout/stderr
> Add basic Android support

- src/formats/h26x.cc
Hi! I'm trying to use `uvgRTP` "directly":
```cmake
cmake_minimum_required(VERSION 3.5)
project(my_project LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
add_executable(my_project main.cpp)
set(UVGRTP_DISABLE_CRYPTO       ON CACHE BOOL "" FORCE)
set(UVGRTP_DISABLE_PRINTS      OFF CACHE BOOL "" FORCE)
set(UVGRTP_DISABLE_WERROR      OFF CACHE BOOL "" FORCE)
set(UVGRTP_DISABLE_TESTS        ON CACHE BOOL "" FORCE)
set(UVGRTP_DISABLE_EXAMPLES     ON CACHE BOOL "" FORCE)
set(UVGRTP_DISABLE_INSTALL      ON CACHE BOOL "" FORCE)
set(UVGRTP_DOWNLOAD_CRYPTO     OFF CACHE BOOL "" FORCE)
set(UVGRTP_RELEASE_COMMIT      OFF CACHE BOOL "" FORCE)
set(DISABLE_CRYPTO      OFF CACHE BOOL "" FORCE)
set(DISABLE_PRINTS      OFF CACHE BOOL "" FORCE)
set(DISABLE_WERROR      OFF …
```
> Update h26x.cc - fixed initialization order of 'dropped_ts_' and 'opped_in_order_'

- src/formats/h26x.cc
Hello, I noticed that there is an issue with RTP frame handling (h264), when receiving a stream with a noticeable packet loss. The crash happens in the following case. Consider the client receiving these RTP frames:
```
Packet seq 100, type = FT_START
Packet seq 101, type = FT_MIDDLE
Packet seq 102, type = FT_END // This packet lost
Packet seq 103, type = FT_START // Reconstructed (deallocated)
Packet seq 104, type = FT_END  // Reconstructed (deallocated)
Packet seq 105, type = FT_START
Packet seq 106, type = FT_END
```
In that case the packet seq 102 was lost. When the library receives seq 104, then it can successfully reconstruct the NAL unit from seq 103, 104 and deallocate them. Then the library receives seq 106 and incorrectly determines the frames 100-106 as continuous and attempts …
> Fixed the issue when reconstructing h264 frames that are not continuous

- src/rtp.cc
Having tested this small patch on continuous streaming on several devices since then and did not see any more crashes.
> Fixing Null pointer in rtp.cc #220

- src/rtp.cc
RTCP SR (and potentially other code) uses rtp::get_rtp_ts() to calculate the RTP SR timestamp value. If push_frame is used with explicit NTP timestamp, get_rtp_ts() always returnes 0 because the member variable rtp::rtp_ts_ is never assigned. This commit adds the missing assignments.
> Fix RTCP SR RTP timestamp value calculation

- docs/README.md
- include/uvgrtp/media_stream.hh
- include/uvgrtp/util.hh
- src/media_stream.cc
- test/test_2_rtp.cpp
Tested with IPv4 on Windows 11 and Linux aarch64.
> Multicast TTL configuration flag added

- src/formats/h26x.cc
Fixes #230 
Removed last byte 0-set old optimisation
> find_h26x_start_code fix

- src/zrtp.cc
- src/zrtp.hh
Fixed gcc-14 warnings about zrtp constructor field init order to match the declaration order
Also removed the double initialization of the dh_finished_ field
> Fixed zrtp class init order and double init warnings on g++-14
